### ISSUE TITLE
1.12.2 Roadmap

### ISSUE THREAD

**Issue by Earthcomputer** [Earthcomputer/multiconnect#10]
- [x] Light crash
- [x] Item remapping
- [x] Item enchantments and custom names
- [x] Block connections
- [x] Stone slabs
- [x] Swimming
- [x] Falling blocks
- [x] Spawn eggs
- [x] Flower pots, banners, mob heads, beds
- [x] Note blocks
- [ ] Entity NBT
- [x] Various errors when changing dimensions
- [x] IndexOutOfBoundsException on Indrit's test server
- [x] Old I18n translations
- [x] Wrong dog collar colour
- [x] Recipes
- [x] Tags
- [x] Commands
- [ ] Invalid entity tooltip in chat
- [x] Slow down swimming

**Comment by Earthcomputer** [comment]
Delivered. Everything still unchecked is moved to separate issues.
