### ISSUE TITLE
1.8 Roadmap

### ISSUE THREAD

**Issue by Earthcomputer** [Earthcomputer/multiconnect#117]
1.8 support is a big step from 1.9. Here is a checklist of things that need to be considered for this update, on top of the normal things that are needed for many updates:

**Combat**
- [ ] Reimplement sword blocking.
- [ ] Remove combat cooldown timers.
- [ ] Block the offhand slot, and the swap hands keybind.
- [ ] Fix potion items.
- [ ] Check knockback works as expected.
- [ ] Make sure players can't push other players.
- [ ] Remove stat.pickup.* and stat.drop.* from menu and commands.
- [ ] Revert blaze powder from brewing stand container.
- [ ] Implement changes in projectile motion.

**Not combat**
- [ ] Fix entity riding (passengers -> riding). Lots of protocol-related things here as well as making sure things work.
- [ ] Reimplement 1.8 boats.
- [ ] Revert parkour mechanics to 1.8.
- [ ] Revert trapdoor climbing.
- [ ] Remove 1.9 options from the command block GUI.
- [ ] Don't create grass paths from right clicking grass with a shovel.
- [ ] Revert placement behaviour of banners, signs, doors and lily pads.
- [ ] Check tool mining speeds.
- [ ] Prevent buckets from being filled from cauldrons.
- [ ] Use cross layout for iron bars and glass panes when there are no connecting blocks.
- [ ] Check whether ender pearls can be thrown in creative.
- [ ] Remove 1.9 achievements.

**Comment by nonetrix** [comment]
intresting
